spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: 
    username: 
    password: 
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 60
      max-lifetime: 60000
      connection-test-query: SELECT 1
      auto-commit: true
      idle-timeout: 180000
      connection-timeout: 30000
sa-token:
  timeout: 2592000
  activityTimeout: 7200
  tokenStyle: tik
  tokenName: token
  isLog: true
  isConcurrent: true
  isShare: false
server:
  port: 18000
  servlet:
    encoding:
      charset: utf-8
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: true
      logic-not-delete-value: false