spring:
  redis:
    port:  #Redis服务器连接的端口
    host:  # Redis服务器的地址
    database: 0 # Redis数据库索引（默认为0
    password: 
    timeout: 5000ms # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: 
    password: 
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 60
      max-lifetime: 60000
      connection-test-query: SELECT 1
      auto-commit: true
      idle-timeout: 180000
      connection-timeout: 30000
sa-token:
  timeout: 2592000
  activityTimeout: 604800
  tokenStyle: tik
  tokenName: token
  isLog: true
  isConcurrent: false
  isShare: false
server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
mybatis-plus:
  global-config:
    banner: false
    enable-sql-runner: true
    db-config:
      logic-delete-field: deleted
      logic-delete-value: true
      logic-not-delete-value: false
logging:
  level:
    wuhan.science.server.mapper: debug
custom:
  roles:
    - 'admin.系统管理员'
    - 'visitor.游客'
  base-types:
    - '科技场馆类'
    - '教育科研与重大工程类'
    - '“三农”类'
    - '企业类'
    - '自然资源类'
    - '其他类'
  news-types:
    - '科技新闻'
    - '科普动态'
    - '活动预告'
  app:
    wx:
      app-id: 
      app-secret: 


